name: "build-test"
on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          npm install
          npm run all
  test-auto-resolving:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
      - run: echo ${{ env.PACKAGE_VERSION }}
  test-manual-path:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          path: 'package.json'
      - run: echo ${{ env.PACKAGE_VERSION }}

